# import = ["~/.config/alacritty/base16_default_dark.toml"]
# import = ["~/.config/alacritty/citylights.toml"] 

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
style = "SemiBold"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
command = { program = "alacritty", args = ["msg", "config", "window.opacity=1.0"] }
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
command = { program = "alacritty", args = ["msg", "config", "-r"] }
key = "R"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "ToggleViMode"

[terminal.shell]
program = "/usr/bin/bash"

[window]
opacity = 0.8

[window.padding]
x = 10
y = 10

[terminal]
osc52 = "CopyPaste"
